id: f4007205613442dd930252becd3cd871
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_335-The_Sutra_on_the_Ringing_Staff-v2
  language: bo
  author: ''
  volume: {}
